name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull codingconcepts53/samplecicd:latest
    - name: Delete Old Container
      run: sudo docker rm -f samplecicd || true
    - name: Run the Docker image
      run: sudo docker run -d --restart unless-stopped -p 8080:8080 --name samplecicd codingconcepts53/samplecicd:latest
    - name: Restart Nginx
      run: sudo systemctl restart nginx
