name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login DockerHub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USER_NAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_USER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t samplecicd . 
    - name: Tag the Docker image
      run: docker tag samplecicd codingconcepts53/samplecicd:latest
    - name: Push to dockerhub
      run: docker push codingconcepts53/samplecicd:latest
